### ISSUE TITLE
Invalid callback id recieved by sendPluginResult

### ISSUE THREAD

**Issue by Ifnir** [ghenry22/cordova-plugin-music-controls2#12]
Play and Pause toggle button on IOS prompts

`Invalid callback id recieved by sendPluginResult`

**Comment by MovingHead** [comment]
Same problem here.

**Comment by SiberianCMS** [comment]
To be sure your remote events are listened be sure to `subscribe` and `listen` before creating the controls like below:

```
MusicControls.subscribe(musicControlsEventsHandler);
MusicControls.listen();
$timeout(function () {
    MusicControls.create(mcDictionnary,
        function () {
            MusicControls.updateIsPlaying(service.isPlaying);
        }, function () {});
}, 20);
```

Otherwise the callbackId will be empty, and remote events will not be handled.

**Comment by ghenry22** [comment]
Thanks for providing an answer to this one!
