### ISSUE TITLE
Ionic android build not working out of the box

### ISSUE THREAD

**Issue by cen1** [ghenry22/cordova-plugin-music-controls2#15]
Steps
```
git clone https://github.com/ionic-team/ionic-conference-app.git
cd ionic-conference-app
npm install
npm install cordova-plugin-music-controls2 --save
ionic cordova plugin add cordova-plugin-music-controls2
```
in src/app/app.module.ts import:
```
import * as MusicControls from 'cordova-plugin-music-controls2/www/MusicControls';
```
followed by
```
ionic cordova build android
```
Results in:

> Task :app:compileDebugJavaWithJavac FAILED
> /home/me/git/ionic-conference-app/platforms/android/app/src/main/java/com/homerours/musiccontrols/MediaSessionCallback.java:5: error: package android.support.v4.media.session does not exist
> import android.support.v4.media.session.MediaSessionCompat;

I am not very experienced with ionic/cordova so I might be doing something wrong. I also noticed there is no angular module exports available so I have to import the library as a native js which is not ideal. That would be a nice addition to the project.

A minimum documentation how to properly include and use the project in an ionic app would also be helpful.

**Comment by ghenry22** [comment]
try adding this plugin to your app:
https://www.npmjs.com/package/cordova-android-support-gradle-release

With this added mine builds out of the box with no issue, I'll look at adding it as a dependency in case it isn't already installed so it gets taken care of automatically.

**Comment by ghenry22** [comment]
Try using the ionic-native music-controls wrapper as well to make it easy to import the functions with proper typing.

**Comment by ghenry22** [comment]
I just released a new version that bundles the support libraries, please give 3.0.4 a try.  I would recommend still keeping the gradle release plugin as well.

**Comment by cen1** [comment]
Thanks, I will try it as soon as time allows and let you know.

**Comment by ghenry22** [comment]
The update to include the support libraries has solved for everyone else I have asked and my test project so I'll close this for now, if you still have issues just let me know.

**Comment by cen1** [comment]
@ghenry22 I tried with 3.0.5 but I get the same error. Can you try to reproduce with the steps from the first post? If you already did that, do you know which Android SDK do you target? It could be that my SDK target is either too old or too new and does not have the package by default.

edit:
After running `cordova plugin add cordova-android-support-gradle-release --fetch --save --variable ANDROID_SUPPORT_VERSION=26` I manage to get further but then it fails with new error:

> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Could not resolve all files for configuration ':app:debugCompileClasspath'.
> > Could not find com.android.support:support-annotations:26.
>   Required by:
>       project :app

Google maven repo seems to be added to build.gradle so not sure what the issue is. I do have Gradle 6 installed globally instead of using built-in from android studio, so I might check that next.
