### ISSUE TITLE
Clicking pause in Android shade doesn't change icon

### ISSUE THREAD

**Issue by kd8ssq** [ghenry22/cordova-plugin-music-controls2#16]
After triggering MusicControls.create(), everything gets created properly in the Android shade and you can see the pause button.  When you click the pause button, the music-controls-pause event is triggered but the icon doesn't change to a play button.  If I force the change using the following code, the iOS duration slider resets: 
```
MusicControls.updateIsPlaying(false); 
MusicControls.updateDismissable(true);
```

Shouldn't Android automatically change from a pause button to a play button just like iOS?

Tested on Android 7 and 10 with the same results.

Android platform 8.1.0
Cordova 9.0.0

**Comment by ghenry22** [comment]
As long as you pause the playing media in the pause event it should update.  I am not currently able to reproduce this issue, have tested on emulator and my HTC android test device and both are working.

Could you try installing the latest update to the plugin, make sure that you're pausing the media in the pause event listener etc and see if it makes any difference?

**Comment by julianCast** [comment]
This may be because of the backdround mode plugin enabled

**Comment by ghenry22** [comment]
I have not been able to reproduce this one, I will assume it was a one off issue but I can't think of anything else to suggest at the moment.
