### ISSUE TITLE
FOREGROUND SERVICE in Android 

### ISSUE THREAD

**Issue by andresbelt** [ghenry22/cordova-plugin-music-controls2#17]
I have a question with the logic of this library because i don't understand, why you don't use FOREGROUND SERVICE in Android? 

it's supposed to be necessary to have something playing in background

thanks

**Comment by ghenry22** [comment]
Hi, the current release 3.0.3 does in fact use the FOREGROUND_SERVICE permission.  You can see it in the plugin.xml
