### ISSUE TITLE
Issue with Android build

### ISSUE THREAD

**Issue by madmandrew** [ghenry22/cordova-plugin-music-controls2#19]
`platforms\android\app\src\main\java\com\homerours\musiccontrols\MusicControls.java:235: error: cannot find symbol`

`playbackstateBuilder.setState(state, PlaybackStateCompat.PLAYBACK_POSITION_UNKNOWN, 0);`
^(this should be under "PlaybackStateCompat.") but formatting won't work
`symbol:   variable PlaybackStateCompat`
`location: class MusicControls`

dependencies
"cordova-android": "8.1.0",
"cordova-plugin-music-controls2": "git+https://github.com/ghenry22/cordova-plugin-music-controls2.git", (also tried version 3.0.3
ionic: 5.20.0

**Comment by MovingHead** [comment]
Same problem. Any updates?

**Comment by ghenry22** [comment]
I can't reproduce this issue when building Android.  One thing to note is that I have this plugin installed to help handle support library conflicts and dependencies with Android builds.  Can you try adding the below to your app?

https://www.npmjs.com/package/cordova-android-support-gradle-release

**Comment by MovingHead** [comment]
I installed the plugin but I still have the same error. Here is the full Error-Message:

BUILD FAILED in 2s
24 actionable tasks: 1 executed, 23 up-to-date
/Users/florian/Documents/Projekte/Mobil/MediApp/MeditationsApp/platforms/android/gradlew: Command failed with exit code 1 Error output:
/Users/florian/Documents/Projekte/Mobil/MediApp/MeditationsApp/platforms/android/app/src/main/java/com/homerours/musiccontrols/MusicControls.java:15: error: package android.support.v4.media does not exist
import android.support.v4.media.MediaMetadataCompat;
                               ^
/Users/florian/Documents/Projekte/Mobil/MediApp/MeditationsApp/platforms/android/app/src/main/java/com/homerours/musiccontrols/MusicControls.java:16: error: package android.support.v4.media.session does not exist
import android.support.v4.media.session.MediaSessionCompat;
                                       ^
/Users/florian/Documents/Projekte/Mobil/MediApp/MeditationsApp/platforms/android/app/src/main/java/com/homerours/musiccontrols/MusicControls.java:17: error: package android.support.v4.media.session does not exist
import android.support.v4.media.session.PlaybackStateCompat;
                                       ^
/Users/florian/Documents/Projekte/Mobil/MediApp/MeditationsApp/platforms/android/app/src/main/java/com/homerours/musiccontrols/MusicControls.java:45: error: cannot find symbol
        private MediaSessionCompat mediaSessionCompat;
                ^
  symbol:   class MediaSessionCompat
  location: class MusicControls
/Users/florian/Documents/Projekte/Mobil/MediApp/MeditationsApp/platforms/android/app/src/main/java/com/homerours/musiccontrols/MediaSessionCallback.java:5: error: package android.support.v4.media.session does not exist
import android.support.v4.media.session.MediaSessionCompat;
                                       ^
/Users/florian/Documents/Projekte/Mobil/MediApp/MeditationsApp/platforms/android/app/src/main/java/com/homerours/musiccontrols/MediaSessionCallback.java:10: error: package MediaSessionCompat does not exist
public class MediaSessionCallback extends MediaSessionCompat.Callback {
                                                            ^
/Users/florian/Documents/Projekte/Mobil/MediApp/MeditationsApp/platforms/android/app/src/main/java/com/homerours/musiccontrols/MusicControls.java:103: error: cannot find symbol
                this.mediaSessionCompat = new MediaSessionCompat(context, "cordova-music-controls-media-session", null, this.mediaButtonPendingIntent);
                                              ^
  symbol:   class MediaSessionCompat
  location: class MusicControls
/Users/florian/Documents/Projekte/Mobil/MediApp/MeditationsApp/platforms/android/app/src/main/java/com/homerours/musiccontrols/MusicControls.java:104: error: cannot find symbol
                this.mediaSessionCompat.setFlags(MediaSessionCompat.FLAG_HANDLES_MEDIA_BUTTONS | MediaSessionCompat.FLAG_HANDLES_TRANSPORT_CONTROLS);
                                                 ^
  symbol:   variable MediaSessionCompat
  location: class MusicControls
/Users/florian/Documents/Projekte/Mobil/MediApp/MeditationsApp/platforms/android/app/src/main/java/com/homerours/musiccontrols/MusicControls.java:104: error: cannot find symbol
                this.mediaSessionCompat.setFlags(MediaSessionCompat.FLAG_HANDLES_MEDIA_BUTTONS | MediaSessionCompat.FLAG_HANDLES_TRANSPORT_CONTROLS);
                                                                                                 ^
  symbol:   variable MediaSessionCompat
  location: class MusicControls
/Users/florian/Documents/Projekte/Mobil/MediApp/MeditationsApp/platforms/android/app/src/main/java/com/homerours/musiccontrols/MusicControls.java:107: error: cannot find symbol
                setMediaPlaybackState(PlaybackStateCompat.STATE_PAUSED);
                                      ^
  symbol:   variable PlaybackStateCompat
  location: class MusicControls
/Users/florian/Documents/Projekte/Mobil/MediApp/MeditationsApp/platforms/android/app/src/main/java/com/homerours/musiccontrols/MusicControls.java:144: error: package MediaMetadataCompat does not exist
                         final MediaMetadataCompat.Builder metadataBuilder = new MediaMetadataCompat.Builder();
                                                  ^
/Users/florian/Documents/Projekte/Mobil/MediApp/MeditationsApp/platforms/android/app/src/main/java/com/homerours/musiccontrols/MusicControls.java:144: error: package MediaMetadataCompat does not exist
                         final MediaMetadataCompat.Builder metadataBuilder = new MediaMetadataCompat.Builder();
                                                                                                    ^
/Users/florian/Documents/Projekte/Mobil/MediApp/MeditationsApp/platforms/android/app/src/main/java/com/homerours/musiccontrols/MusicControls.java:152: error: cannot find symbol
                                        metadataBuilder.putString(MediaMetadataCompat.METADATA_KEY_TITLE, infos.track);
                                                                  ^
  symbol: variable MediaMetadataCompat
/Users/florian/Documents/Projekte/Mobil/MediApp/MeditationsApp/platforms/android/app/src/main/java/com/homerours/musiccontrols/MusicControls.java:154: error: cannot find symbol
                                        metadataBuilder.putString(MediaMetadataCompat.METADATA_KEY_ARTIST, infos.artist);
                                                                  ^
  symbol: variable MediaMetadataCompat
/Users/florian/Documents/Projekte/Mobil/MediApp/MeditationsApp/platforms/android/app/src/main/java/com/homerours/musiccontrols/MusicControls.java:156: error: cannot find symbol
                                        metadataBuilder.putString(MediaMetadataCompat.METADATA_KEY_ALBUM, infos.album);
                                                                  ^
  symbol: variable MediaMetadataCompat
/Users/florian/Documents/Projekte/Mobil/MediApp/MeditationsApp/platforms/android/app/src/main/java/com/homerours/musiccontrols/MusicControls.java:160: error: cannot find symbol
                                                metadataBuilder.putBitmap(MediaMetadataCompat.METADATA_KEY_ALBUM_ART, art);
                                                                          ^
  symbol: variable MediaMetadataCompat
/Users/florian/Documents/Projekte/Mobil/MediApp/MeditationsApp/platforms/android/app/src/main/java/com/homerours/musiccontrols/MusicControls.java:161: error: cannot find symbol
                                                metadataBuilder.putBitmap(MediaMetadataCompat.METADATA_KEY_ART, art);
                                                                          ^
  symbol: variable MediaMetadataCompat
/Users/florian/Documents/Projekte/Mobil/MediApp/MeditationsApp/platforms/android/app/src/main/java/com/homerours/musiccontrols/MusicControls.java:168: error: cannot find symbol
                                                setMediaPlaybackState(PlaybackStateCompat.STATE_PLAYING);
                                                                      ^
  symbol: variable PlaybackStateCompat
/Users/florian/Documents/Projekte/Mobil/MediApp/MeditationsApp/platforms/android/app/src/main/java/com/homerours/musiccontrols/MusicControls.java:170: error: cannot find symbol
                                                setMediaPlaybackState(PlaybackStateCompat.STATE_PAUSED);
                                                                      ^
  symbol: variable PlaybackStateCompat
/Users/florian/Documents/Projekte/Mobil/MediApp/MeditationsApp/platforms/android/app/src/main/java/com/homerours/musiccontrols/MusicControls.java:182: error: cannot find symbol
                                setMediaPlaybackState(PlaybackStateCompat.STATE_PLAYING);
                                                      ^
  symbol:   variable PlaybackStateCompat
  location: class MusicControls
/Users/florian/Documents/Projekte/Mobil/MediApp/MeditationsApp/platforms/android/app/src/main/java/com/homerours/musiccontrols/MusicControls.java:184: error: cannot find symbol
                                setMediaPlaybackState(PlaybackStateCompat.STATE_PAUSED);
                                                      ^
  symbol:   variable PlaybackStateCompat
  location: class MusicControls
/Users/florian/Documents/Projekte/Mobil/MediApp/MeditationsApp/platforms/android/app/src/main/java/com/homerours/musiccontrols/MusicControls.java:225: error: package PlaybackStateCompat does not exist
                PlaybackStateCompat.Builder playbackstateBuilder = new PlaybackStateCompat.Builder();
                                   ^
/Users/florian/Documents/Projekte/Mobil/MediApp/MeditationsApp/platforms/android/app/src/main/java/com/homerours/musiccontrols/MusicControls.java:225: error: package PlaybackStateCompat does not exist
                PlaybackStateCompat.Builder playbackstateBuilder = new PlaybackStateCompat.Builder();
                                                                                          ^
/Users/florian/Documents/Projekte/Mobil/MediApp/MeditationsApp/platforms/android/app/src/main/java/com/homerours/musiccontrols/MusicControls.java:226: error: cannot find symbol
                if( state == PlaybackStateCompat.STATE_PLAYING ) {
                             ^
  symbol:   variable PlaybackStateCompat
  location: class MusicControls
/Users/florian/Documents/Projekte/Mobil/MediApp/MeditationsApp/platforms/android/app/src/main/java/com/homerours/musiccontrols/MusicControls.java:227: error: cannot find symbol
                        playbackstateBuilder.setActions(PlaybackStateCompat.ACTION_PLAY_PAUSE | PlaybackStateCompat.ACTION_PAUSE | PlaybackStateCompat.ACTION_SKIP_TO_NEXT | PlaybackStateCompat.ACTION_SKIP_TO_PREVIOUS |
                                                        ^
  symbol:   variable PlaybackStateCompat
  location: class MusicControls
/Users/florian/Documents/Projekte/Mobil/MediApp/MeditationsApp/platforms/android/app/src/main/java/com/homerours/musiccontrols/MusicControls.java:227: error: cannot find symbol
                        playbackstateBuilder.setActions(PlaybackStateCompat.ACTION_PLAY_PAUSE | PlaybackStateCompat.ACTION_PAUSE | PlaybackStateCompat.ACTION_SKIP_TO_NEXT | PlaybackStateCompat.ACTION_SKIP_TO_PREVIOUS |
                                                                                                ^
  symbol:   variable PlaybackStateCompat
  location: class MusicControls
/Users/florian/Documents/Projekte/Mobil/MediApp/MeditationsApp/platforms/android/app/src/main/java/com/homerours/musiccontrols/MusicControls.java:227: error: cannot find symbol
                        playbackstateBuilder.setActions(PlaybackStateCompat.ACTION_PLAY_PAUSE | PlaybackStateCompat.ACTION_PAUSE | PlaybackStateCompat.ACTION_SKIP_TO_NEXT | PlaybackStateCompat.ACTION_SKIP_TO_PREVIOUS |
                                                                                                                                   ^
  symbol:   variable PlaybackStateCompat
  location: class MusicControls
/Users/florian/Documents/Projekte/Mobil/MediApp/MeditationsApp/platforms/android/app/src/main/java/com/homerours/musiccontrols/MusicControls.java:227: error: cannot find symbol
                        playbackstateBuilder.setActions(PlaybackStateCompat.ACTION_PLAY_PAUSE | PlaybackStateCompat.ACTION_PAUSE | PlaybackStateCompat.ACTION_SKIP_TO_NEXT | PlaybackStateCompat.ACTION_SKIP_TO_PREVIOUS |
                                                                                                                                                                             ^
  symbol:   variable PlaybackStateCompat
  location: class MusicControls
/Users/florian/Documents/Projekte/Mobil/MediApp/MeditationsApp/platforms/android/app/src/main/java/com/homerours/musiccontrols/MusicControls.java:228: error: cannot find symbol
                                PlaybackStateCompat.ACTION_PLAY_FROM_MEDIA_ID |
                                ^
  symbol:   variable PlaybackStateCompat
  location: class MusicControls
/Users/florian/Documents/Projekte/Mobil/MediApp/MeditationsApp/platforms/android/app/src/main/java/com/homerours/musiccontrols/MusicControls.java:229: error: cannot find symbol
                                PlaybackStateCompat.ACTION_PLAY_FROM_SEARCH);
                                ^
  symbol:   variable PlaybackStateCompat
  location: class MusicControls
/Users/florian/Documents/Projekte/Mobil/MediApp/MeditationsApp/platforms/android/app/src/main/java/com/homerours/musiccontrols/MusicControls.java:230: error: cannot find symbol
                        playbackstateBuilder.setState(state, PlaybackStateCompat.PLAYBACK_POSITION_UNKNOWN, 1.0f);
                                                             ^
  symbol:   variable PlaybackStateCompat
  location: class MusicControls
/Users/florian/Documents/Projekte/Mobil/MediApp/MeditationsApp/platforms/android/app/src/main/java/com/homerours/musiccontrols/MusicControls.java:232: error: cannot find symbol
                        playbackstateBuilder.setActions(PlaybackStateCompat.ACTION_PLAY_PAUSE | PlaybackStateCompat.ACTION_PLAY | PlaybackStateCompat.ACTION_SKIP_TO_NEXT | PlaybackStateCompat.ACTION_SKIP_TO_PREVIOUS |
                                                        ^
  symbol:   variable PlaybackStateCompat
  location: class MusicControls
/Users/florian/Documents/Projekte/Mobil/MediApp/MeditationsApp/platforms/android/app/src/main/java/com/homerours/musiccontrols/MusicControls.java:232: error: cannot find symbol
                        playbackstateBuilder.setActions(PlaybackStateCompat.ACTION_PLAY_PAUSE | PlaybackStateCompat.ACTION_PLAY | PlaybackStateCompat.ACTION_SKIP_TO_NEXT | PlaybackStateCompat.ACTION_SKIP_TO_PREVIOUS |
                                                                                                ^
  symbol:   variable PlaybackStateCompat
  location: class MusicControls
/Users/florian/Documents/Projekte/Mobil/MediApp/MeditationsApp/platforms/android/app/src/main/java/com/homerours/musiccontrols/MusicControls.java:232: error: cannot find symbol
                        playbackstateBuilder.setActions(PlaybackStateCompat.ACTION_PLAY_PAUSE | PlaybackStateCompat.ACTION_PLAY | PlaybackStateCompat.ACTION_SKIP_TO_NEXT | PlaybackStateCompat.ACTION_SKIP_TO_PREVIOUS |
                                                                                                                                  ^
  symbol:   variable PlaybackStateCompat
  location: class MusicControls
/Users/florian/Documents/Projekte/Mobil/MediApp/MeditationsApp/platforms/android/app/src/main/java/com/homerours/musiccontrols/MusicControls.java:232: error: cannot find symbol
                        playbackstateBuilder.setActions(PlaybackStateCompat.ACTION_PLAY_PAUSE | PlaybackStateCompat.ACTION_PLAY | PlaybackStateCompat.ACTION_SKIP_TO_NEXT | PlaybackStateCompat.ACTION_SKIP_TO_PREVIOUS |
                                                                                                                                                                            ^
  symbol:   variable PlaybackStateCompat
  location: class MusicControls
/Users/florian/Documents/Projekte/Mobil/MediApp/MeditationsApp/platforms/android/app/src/main/java/com/homerours/musiccontrols/MusicControls.java:233: error: cannot find symbol
                                PlaybackStateCompat.ACTION_PLAY_FROM_MEDIA_ID |
                                ^
  symbol:   variable PlaybackStateCompat
  location: class MusicControls
/Users/florian/Documents/Projekte/Mobil/MediApp/MeditationsApp/platforms/android/app/src/main/java/com/homerours/musiccontrols/MusicControls.java:234: error: cannot find symbol
                                PlaybackStateCompat.ACTION_PLAY_FROM_SEARCH);
                                ^
  symbol:   variable PlaybackStateCompat
  location: class MusicControls
/Users/florian/Documents/Projekte/Mobil/MediApp/MeditationsApp/platforms/android/app/src/main/java/com/homerours/musiccontrols/MusicControls.java:235: error: cannot find symbol
                        playbackstateBuilder.setState(state, PlaybackStateCompat.PLAYBACK_POSITION_UNKNOWN, 0);
                                                             ^
  symbol:   variable PlaybackStateCompat
  location: class MusicControls
/Users/florian/Documents/Projekte/Mobil/MediApp/MeditationsApp/platforms/android/app/src/main/java/com/homerours/musiccontrols/MediaSessionCallback.java:18: error: method does not override or implement a method from a supertype
  @Override
  ^
/Users/florian/Documents/Projekte/Mobil/MediApp/MeditationsApp/platforms/android/app/src/main/java/com/homerours/musiccontrols/MediaSessionCallback.java:20: error: cannot find symbol
    super.onPlay();
    ^
  symbol:   variable super
  location: class MediaSessionCallback
/Users/florian/Documents/Projekte/Mobil/MediApp/MeditationsApp/platforms/android/app/src/main/java/com/homerours/musiccontrols/MediaSessionCallback.java:27: error: method does not override or implement a method from a supertype
  @Override
  ^
/Users/florian/Documents/Projekte/Mobil/MediApp/MeditationsApp/platforms/android/app/src/main/java/com/homerours/musiccontrols/MediaSessionCallback.java:29: error: cannot find symbol
    super.onPause();
    ^
  symbol:   variable super
  location: class MediaSessionCallback
/Users/florian/Documents/Projekte/Mobil/MediApp/MeditationsApp/platforms/android/app/src/main/java/com/homerours/musiccontrols/MediaSessionCallback.java:36: error: method does not override or implement a method from a supertype
  @Override
  ^
/Users/florian/Documents/Projekte/Mobil/MediApp/MeditationsApp/platforms/android/app/src/main/java/com/homerours/musiccontrols/MediaSessionCallback.java:38: error: cannot find symbol
    super.onSkipToNext();
    ^
  symbol:   variable super
  location: class MediaSessionCallback
/Users/florian/Documents/Projekte/Mobil/MediApp/MeditationsApp/platforms/android/app/src/main/java/com/homerours/musiccontrols/MediaSessionCallback.java:45: error: method does not override or implement a method from a supertype
  @Override
  ^
/Users/florian/Documents/Projekte/Mobil/MediApp/MeditationsApp/platforms/android/app/src/main/java/com/homerours/musiccontrols/MediaSessionCallback.java:47: error: cannot find symbol
    super.onSkipToPrevious();
    ^
  symbol:   variable super
  location: class MediaSessionCallback
/Users/florian/Documents/Projekte/Mobil/MediApp/MeditationsApp/platforms/android/app/src/main/java/com/homerours/musiccontrols/MediaSessionCallback.java:54: error: method does not override or implement a method from a supertype
  @Override
  ^
/Users/florian/Documents/Projekte/Mobil/MediApp/MeditationsApp/platforms/android/app/src/main/java/com/homerours/musiccontrols/MediaSessionCallback.java:56: error: cannot find symbol
    super.onPlayFromMediaId(mediaId, extras);
    ^
  symbol:   variable super
  location: class MediaSessionCallback
/Users/florian/Documents/Projekte/Mobil/MediApp/MeditationsApp/platforms/android/app/src/main/java/com/homerours/musiccontrols/MediaSessionCallback.java:59: error: method does not override or implement a method from a supertype
  @Override
  ^
/Users/florian/Documents/Projekte/Mobil/MediApp/MeditationsApp/platforms/android/app/src/main/java/com/homerours/musiccontrols/MediaSessionCallback.java:64: error: cannot find symbol
      return super.onMediaButtonEvent(mediaButtonIntent);
             ^
  symbol:   variable super
  location: class MediaSessionCallback
/Users/florian/Documents/Projekte/Mobil/MediApp/MeditationsApp/platforms/android/app/src/main/java/com/homerours/musiccontrols/MediaSessionCallback.java:131: error: cannot find symbol
          return super.onMediaButtonEvent(mediaButtonIntent);
                 ^
  symbol:   variable super
  location: class MediaSessionCallback
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/florian/Documents/Projekte/Mobil/MediApp/MeditationsApp/platforms/android/app/src/main/java/org/apache/cordova/file/AssetFilesystem.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
51 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by jeremywj** [comment]
Exact same issue here

**Comment by ghenry22** [comment]
Ah ok maybe I didn't see the issue because another plugin had already included the support library.

I have merged an update to include the support libraries with the plugin, could you please try installing latest from NPM and you should get version 3.0.4.

I would still recommend keeping the previously mentioned plugin as it will handle conflicting support library requirements between plugins.

**Comment by jeremywj** [comment]
Crazy... I just did this about 2 minutes ago...

cordova plugin remove cordova-plugin-music-controls2
cordova plugin add cordova-plugin-music-controls2@3.0.4

and it fixed the issue.  I thought I worked some miracle by forcing it to install the latest version which somehow didn't get installed by itself.  Turns out you just updated it probably seconds before I could issue that command.

**Comment by MovingHead** [comment]
Thank you @ghenry22, the problem is fixed :)

**Comment by madmandrew** [comment]
Awesome it works now!!!

I had additional conflicts with firebase plugins being installed, this stackoverflow post helped resolve remaining conflicts

https://stackoverflow.com/questions/56688570/program-type-already-present-android-support-v4-os-resultreceivermyresultrecei

**Comment by ghenry22** [comment]
https://www.npmjs.com/package/cordova-android-support-gradle-release
This plugin hels resolve conflicting support library versions in different plugins, if you check the readme on that repo you can see that he also has a plugin that handles conflicts with firebase and a few other common scenarios.  I have found these generally to be really useful for avoiding weird conflicts.
