### ISSUE TITLE
Requires BLUETOOTH and BLUETOOTH_ADMIN permissions on Android

### ISSUE THREAD

**Issue by decates** [ghenry22/cordova-plugin-music-controls2#21]
I'm using version 3.0.3, and just switched from the [old repo](https://github.com/homerours/cordova-music-controls-plugin) to fix an issue with iOS (thank you!). 

However, it looks like `plugin.xml` for this plugin is now requesting additional permissions on Android, including `android.permission.BLUETOOTH` and `android.permission.BLUETOOTH_ADMIN`. 

The [commit](https://github.com/ghenry22/cordova-plugin-music-controls2/commit/fca0875c1a45fe9afa30637e6408420027eed47d) in which this change was made simply has the comment 'update package name ready for publish', so I wonder if this is an accidental change that shouldn't be included? If not, what's the reason for requesting these additional permissions on Android? Thanks.

**Comment by SiberianCMS** [comment]
For me, it looks like it's specific the @ghenry22 needs, so you may want to remove them.

We did, and it works ok without both.

**Comment by decates** [comment]
OK, that's helpful to hear @SiberianCMS , thanks. It would also be useful to hear from @ghenry22 to confirm, and then perhaps I can raise a PR to remove those permissions?

**Comment by ghenry22** [comment]
@decates the addition of the bluetooth permission was trying to get metadata displaying properly on bluetooth devices and to resolve some remote control event issues with certain bluetooth devices.  It shouldn't need the ADMIN privilege though, just the regular bluetooth, I think that crept in accidentally during testing.

I'll release an update to clean this up.

**Comment by decates** [comment]
Thanks @ghenry22 - I'll raise a PR to make it easier for you (and to allow us to continue without waiting for the change to appear in npm).

**Comment by decates** [comment]
PR merged, closing this. Thanks @ghenry22 !
