### ISSUE TITLE
Android - Events not firing from lock screen

### ISSUE THREAD

**Issue by cal2go** [ghenry22/cordova-plugin-music-controls2#23]
On Android 9 - Samsung Galaxy A70.   Events (play/pause/next/previous) are not being recorded from the lock screen.  Works fine from the notification tray.

On emulators, it works fine and as expected.

**Comment by GalacticWeb** [comment]
+1 having the same problem

**Comment by petenickless** [comment]
+1 still seeing this issue

**Comment by jaipresto** [comment]
The solution is to listen for the event `music-controls-media-button-play-pause`, not just `music-controls-media-button`.

**Comment by ghenry22** [comment]
Reviewing and merging some PRs shortly and will ensure to get this included

**Comment by ghenry22** [comment]
This should be resolved in 3.0.6 which was just released.  The problem was due to different key codes coming from the notification and from the lockscreen / headsets and other devices.
