### ISSUE TITLE
iOS Lock Screen Controls Only Show Intermittently

### ISSUE THREAD

**Issue by odyssey-skin-and-health** [ghenry22/cordova-plugin-music-controls2#24]
I am using cordova-plugin-media and this plugin to play music and provide controls for users on the home screen for iOS. The below implementation is not entirely finished, but is at a point where it should work. My issue is that the controls only sometimes appear, other times nothing shows at all, and sometimes the controls show, but then disappear after a few minutes. Can anyone provide insight into how I can get the controls to always show, instead of randomly working some of the time after an app restart? It is the exact same code every times.

I have the background audio capability turned on inside my xcode project too.

`import AudioPlayerStore, { IAudioPlayerMetadata } from "../../../main/sharedStores/AudioPlayerStore";
import { IAudioPlayer } from "../interfaces/IAudioPlayer";

/** How often the duration is updated */
const TIMER_UPDATE: number = 1000;

declare var MusicControls: any;

/** The amount of time to skip forward and back */
const SKIP_DURATION_IN_SECONDS: number = 15;

export class CordovaAudioPlayer implements IAudioPlayer
{
    // Varaibles
    // =======================================

    /** The instance of the cordova audio player */
    private audioPlayer!: Media;

    /** The reference to the timeout */
    private updateTime: number = 0;

    /** Whether or not the current audio is loading */
    public isLoading: boolean = false;

    /** The current time (in seconds) of the audio */
    public currentTime: number = 0;

    /** The total duration (in seconds) of the audio */
    public duration: number = 0;

    // Setup
    // =======================================

    constructor(public metaData: IAudioPlayerMetadata)
    {
        this.audioPlayer = new Media(
            this.metaData.source,
            this.onPlayEnded.bind(this),
            this.onError.bind(this),
            this.statusChange.bind(this)
        );

        this.isLoading = true;
        this.play();
    }

    // Implements
    // =======================================

    /**
     * Play the audio
     */
    public play(): void { this.audioPlayer.play(); }

    /**
     * Pause the audio
     */
    public pause(): void { this.audioPlayer.pause(); }

    /**
     * Reset the player
     */
    public reset(): void
    {
        this.audioPlayer.stop();
        this.audioPlayer.release();
    }

    /**
     * Update the players current time
     *
     * @param time the new current time to set
     */
    public setCurrentTime(time: number): void
    {
        this.audioPlayer.seekTo(time * 1000);
        this.currentTime = time;

        MusicControls.updateElapsed({ elapsed: time });
    }

    private async statusChange(code: number): Promise<void>
    {
        switch (code)
        {
            case Media.MEDIA_NONE:
                console.log("No media")
                break

            case Media.MEDIA_STARTING:
                console.log("Media starting");
                break

            case Media.MEDIA_RUNNING:
                console.log("Media running");

                this.duration = this.audioPlayer.getDuration();
                this.updateTime = setInterval(this.updateCurrentTime.bind(this), TIMER_UPDATE);
                this.updateCurrentTime();

                MusicControls.create({
                    track: this.metaData.title,
                    artist: this.metaData.author,
                    hasSkipForward: true,
                    hasSkipBackward: true,
                    skipForwardInterval: 15,
                    skipBackwardInterval: 15,
                    duration: this.duration,
                    elapsed: this.currentTime,
                }, () =>
                {
                    console.log("Success but never gets called")
                }, this.onError.bind(this));

                MusicControls.subscribe(this.events.bind(this));
                MusicControls.listen();
                MusicControls.updateIsPlaying(true);

                AudioPlayerStore.instance.setIsPlaying(true);
                this.isLoading = false;

                break;

            case Media.MEDIA_PAUSED:
                clearInterval(this.updateTime);
                MusicControls.updateIsPlaying(false);
                AudioPlayerStore.instance.setIsPlaying(false);
                break;

            case Media.MEDIA_STOPPED:
                clearInterval(this.updateTime);
                this.isLoading = false;
                this.currentTime = 0;
                this.duration = 0;
                MusicControls.destroy();
                break;

            default:
                break;
        }
    }

    // Helpers
    // =======================================

    /**
     * Get the current players position wrapped in a promise
     */
    private async getPlayerPosition(): Promise<number>
    {
        return new Promise<number>((resolve, reject) =>
        {
            this.audioPlayer
                .getCurrentPosition((currentTime: number) => resolve(currentTime), (error: any) => reject(error))
        });
    }

    private onPlayEnded(): void { AudioPlayerStore.instance.setIsPlaying(false); }

    private events(action: string): void
    {
        const message = JSON.parse(action).message;
        switch (message)
        {
            case 'music-controls-skip-forward':
                const newForwardTime: number = Math.min(this.currentTime + SKIP_DURATION_IN_SECONDS, this.duration);
                this.setCurrentTime(newForwardTime);
                break;
            case 'music-controls-skip-backward':
                const newBackwardTime: number = Math.max(this.currentTime - SKIP_DURATION_IN_SECONDS, 0);
                this.setCurrentTime(newBackwardTime);
                break;
            case 'music-controls-pause':
                this.audioPlayer.pause(); 
                break;
            case 'music-controls-play':
                this.audioPlayer.play();
                break;
            case 'music-controls-destroy':
                // Do something
                break;

            // External controls (iOS only)
            case 'music-controls-toggle-play-pause':
                // Do something
                break;
            case 'music-controls-seek-to':
                const seekToInSeconds = JSON.parse(action).position;
                this.setCurrentTime(seekToInSeconds);
                break;

            default:
                break;
        }
    }

    private onError(err: any)
    {
        console.log(err);
    }

    private async updateCurrentTime(): Promise<void>
    {
        const elapsed: number = await this.getPlayerPosition();
        this.currentTime = elapsed;
        MusicControls.updateElapsed({ elapsed });
    }
}
`

**Comment by odyssey-skin-and-health** [comment]
Turns out it was not working because of this config setting I had:
<feature name="IntentAndNavigationFilter">
        <param name="ios-package" value="CDVIntentAndNavigationFilter" />
        <param name="onload" value="true" />
    </feature>

**Comment by jahangirdevs** [comment]
> Turns out it was not working because of this config setting I had:

What are the right config settings please tell. Thanks
