### ISSUE TITLE
Background Color

### ISSUE THREAD

**Issue by bryanjorgeflores** [ghenry22/cordova-plugin-music-controls2#26]
Could you add an option to custom the background from the notification? Something like the react native plugin

**Comment by ghenry22** [comment]
Do you have a link to the repo for the react native plugin you mentioned?  I'll have a look at how they have implemented and see if we can do the same.

**Comment by bryanjorgeflores** [comment]
Sure. https://github.com/tanguyantoine/react-native-music-control

**Comment by ghenry22** [comment]
closing as duplicate see #38
