### ISSUE TITLE
Random crashes updateNotification

### ISSUE THREAD

**Issue by julianCast** [ghenry22/cordova-plugin-music-controls2#32]
Hi, at random times the app crashes right in the beginning, the errors that play console report are the following:
Both from the updateNotification function. Any idea? Thank you! 

![IMG_20200916_212142](https://user-images.githubusercontent.com/559677/93382629-abbd1300-f862-11ea-8212-9295f4b6fa8b.jpg)

**Comment by ghenry22** [comment]
I haven't seen that before but I'll take a look at it and see if I can find anything.

**Comment by ghenry22** [comment]
Are you playing audio before you try to update the the music controls?

**Comment by julianCast** [comment]
> Are you playing audio before you try to update the the music controls?

Let me check that, I know I'm only using:

I'm playing HML5 audio, and then calling create method from musicControls. But apparently play() [can return a promise
](https://developers.google.com/web/updates/2016/03/play-returns-promise) so I'll try like that.

Although this crashes ONLY happens the first time, the thing is, every time a track ends, Im calling musicControls.create() to update title and author, is that the way?

Functions I'm using:
MusicControls.updateIsPlaying(true);
MusicControls.updateElapsed({ elapsed: seekToInSeconds,isPlaying: true });

**Comment by julianCast** [comment]
I wrapped the play function, now I only call create once play is successful, but it still happening :(

**Comment by ghenry22** [comment]
I'll do some testing.

I'd suggest dropping the updateIsPlaying call as it's not needed the remote controls will reflect the state of the audio automatically.

Basic usage would be:

FIRST PLAY:
Play audio
create music controls
SUBSEQUENT PLAY:
release music controls (to destroy the old one)
create music controls

try this and dropping the updateIsPlaying and updateElapsed calls and see if you still see any errors.  It's important to release the old music control before calling create again for the next track.  I think the readme on the repo shows this as well for reference, but I'll check if it needs updating.

**Comment by julianCast** [comment]
So, I dropped updateIsPlaying  and updateElapsed and now I destroy the music controls before creating it.
But now the control remote does not reflect the paused/resume state changes.

To play the audio I'm using :
```
this.soundtrack = new Audio()
this.soundtrack.play() and this.soundtrack.pause()
```
Using HTML 5 audio tag doesn't update music controls maybe?

**Comment by ghenry22** [comment]
HTML audio doesn't work properly with the remote controls, the status and metadata will be overriden by the browser.  You need to use the cordova media plugin to play your media then all should play nice.
This has been a problem as long as this plugin as been around as the browser overrides the playback controls when using html audio tag.

**Comment by julianCast** [comment]
Thank you! I'll use native media plugin
