### ISSUE TITLE
change the background color according to the image

### ISSUE THREAD

**Issue by rcasunshare** [ghenry22/cordova-plugin-music-controls2#33]
This plugin allows you to change the background color of the notification according to the image of the song that is displayed?
To look like this example?

![50876941-94732480-13f5-11e9-8002-daa77ff85c3a](https://user-images.githubusercontent.com/12421510/93652123-50b62800-f9ea-11ea-83c8-a47b80fedc52.png)

**Comment by ghenry22** [comment]
This plugin does not have this kind of functionality at the moment.

**Comment by rcasunshare** [comment]
> This plugin does not have this kind of functionality at the moment.

Can this be implemented?

**Comment by ghenry22** [comment]
Closing as duplicate see #38
