### ISSUE TITLE
Background image does not change

### ISSUE THREAD

**Issue by rcasunshare** [ghenry22/cordova-plugin-music-controls2#34]
Background image does not change after two songs using streaming radio source.

**Comment by rcasunshare** [comment]
The application running in the background does not change the information of the song name and cover after two songs.

**Comment by ghenry22** [comment]
Are you using HTML5 audio or the cordova media plugin?  HTML audio will interfere with the remote controls and override the values that you set.  We haven't been able to find a way to work around this to date.

**Comment by rcasunshare** [comment]
Hi, I use Exoplayer with Background mode.  The problem I think is in the setinterval that freezes after 10 minutes, I use streaming source with metadata with iTunes to show the image with the song title. But apparently after two songs it doesn't change anymore until the application is reopened.

**Comment by ghenry22** [comment]
You will probably need to grab the background mode cordova plugin to stop the webview being suspended in the background for battery optimization.  Once the webview is suspended then, as you say, any javascript processing will stop until the app comes back to the foreground and that includes updating the remote controls metadata.
