### ISSUE TITLE
Play button always displayed

### ISSUE THREAD

**Issue by CharlesOnAir** [ghenry22/cordova-plugin-music-controls2#35]
Hello,

I am using your plugin for my application, at the moment I am having two problems.

The first is that I can't change the state of the play button, it is always displayed in play.

The second is when I decided to close my iOs to test the player from the lockscreen, my player disappears to display a pleasure with only "Ionic App" for information.

Thanks for your help !

**Comment by ghenry22** [comment]
Responded to your other issue, closing as duplicate.
