### ISSUE TITLE
Android & iOS necessary settings

### ISSUE THREAD

**Issue by AntonERG** [ghenry22/cordova-plugin-music-controls2#40]
@ghenry22 

Great job!
That will be nice if you will add to the installation section suggestions for necessary settings for **src-cordova/config.xml** file

For Android - inside `<platform name="android">`:
```
<config-file target="AndroidManifest.xml" parent="/*">
  <uses-permission android:name="android.permission.WAKE_LOCK" />
</config-file>
```

For iOS - inside `<platform name="ios">`:
```
<config-file target="*-Info.plist" parent="UIBackgroundModes">
  <array>
    <string>audio</string>
  </array>
</config-file>
```

**Comment by ghenry22** [comment]
For android wake_lock is already included with the plugin, no need to add it to config.xml.

For iOS you can add you required background modes through xcode.  I am not sure that I want to push them from this plugin as people will often have different use cases for background mode.  I'll consider whether to add here ot not.
