### ISSUE TITLE
I can't import 

### ISSUE THREAD

**Issue by pickkck** [ghenry22/cordova-plugin-music-controls2#42]
Hi, 
I tried to use this plugin but when i try to import the module i had error, the error is like it, 
'Cannot find module 'cordova-plugin-music-controls2' or its corresponding type declarations'
i don't know if im doing someting wrong but if anyone can helpme, thanks

**Comment by keyamasabaya** [comment]
Did you use npm ?
No problem with importing and emulate or run via cordova

**Comment by ghenry22** [comment]
Check the readme, there are 2 ways to install, either by npm for the latest published version or directly from this repo for bleeding edge.

Have just tested both, both are working.

**Comment by PaulCombal** [comment]
@pickkck I look like an idiot, but I have the same issue
```bash
$ npm i cordova-plugin-music-controls2
```
```javascript
import {MusicControls} from 'cordova-plugin-music-controls2'
```
```
This dependency was not found:

* cordova-plugin-music-controls2 in ./src/js/mediaControls.js
```
I'm using the Vue Quasar framework.

Did you fix your issue?

**Comment by pickkck** [comment]
Hi, when i try to use this, was in a Ionic project, i can not fix this error, but i create an other project in an other computer and the plugin works, i don't know whats is the problem, maybe a problem of versions
