### ISSUE TITLE
 Android Platform - On App Close Notification Disappears [ Capacitor Integrations ]

### ISSUE THREAD

**Issue by nawing** [ghenry22/cordova-plugin-music-controls2#43]

**Comment by tbassett44** [comment]
I am seeing this as well.  Android notification on Android 7.1.1 goes away as soon as app is closed or phone is put to sleep.  If i swipe down on the tray while the app is showing, the music player is there.

**Comment by ghenry22** [comment]
@tbassett44 you mean the notification goes away when the app goes to the background?  The whole point of it is that it stays there when the app is in the background to provide remote controls.  If you can confirm I will take a look.

Are you using Cordova or Capacitor?  What versions?

**Comment by ABT-kachin** [comment]
Cordova builds works fine, Capacitor build got problems. I fixed it by adding, platform directive - which is not neat, but it serves the purpose for now. 

this.platform.pause.subscribe(e => this.setupcontrol( ));

  /**
   * setupcontrol( )
   */
  async setupcontrol( ): Promise < void > {
    this.control.create({
      track: this.musicInt.songTitle,
      artist: this.musicInt.songArtist.artistName,
      cover: this.musicInt.songCover,
      isPlaying: this.musicInt.isPlaying,
      dismissable: false,
      hasClose: false,
      album: this.musicInt.songAlbum.albumName,
      duration: this.musicInt.duration,
      playIcon: 'media_play',
      pauseIcon: 'media_pause',
      prevIcon: 'media_prev',
      nextIcon: 'media_next',
      closeIcon: 'media_close',
      notificationIcon: 'notification'
    });
    try {
      this.control.subscribe( ).subscribe((action) =>
      {
        const message = JSON.parse(action).message;
        switch (message) {
          case 'music-controls-next':this.next().then((song)=>this.initialize(song));break;
          case 'music-controls-previous':this.prev().then((song)=>this.initialize(song));break;
          case 'music-controls-pause':this.pause();break;
          case 'music-controls-play':this.play();break;
          case 'music-controls-destroy':this.release();break;

          case 'music-controls-media-button-next':this.next().then((song)=>this.initialize(song));break;
          case 'music-controls-media-button-previous':this.prev().then((song)=>this.initialize(song));break;
          case 'music-controls-media-button-pause':this.pause();break;
          case 'music-controls-media-button-play':this.play();break;
          case 'music-controls-media-button-play-pause':this.tooglepp();break;
          case 'music-controls-media-button-headset-hook':this.pause();break;
          default: break;
        }
      });
    } catch (error) {
      console.log(error)
    }
    this.control.listen( );
    this.control.updateIsPlaying(true);
  }

**Comment by nawing** [comment]
Cordova builds works fine, Capacitor build got problems. I fixed it by adding, platform directive - which is not neat, but it serves the purpose for now.

**this.platform.pause.subscribe(e => this.setupcontrol( ));**

async setupcontrol( ): Promise < void > {
this.control.create({
track: this.musicInt.songTitle,
artist: this.musicInt.songArtist.artistName,
cover: this.musicInt.songCover,
isPlaying: this.musicInt.isPlaying,
dismissable: false,
hasClose: false,
album: this.musicInt.songAlbum.albumName,
duration: this.musicInt.duration,
playIcon: 'media_play',
pauseIcon: 'media_pause',
prevIcon: 'media_prev',
nextIcon: 'media_next',
closeIcon: 'media_close',
notificationIcon: 'notification'
});
try {
this.control.subscribe( ).subscribe((action) =>
{
const message = JSON.parse(action).message;
switch (message) {
case 'music-controls-next':this.next().then((song)=>this.initialize(song));break;
case 'music-controls-previous':this.prev().then((song)=>this.initialize(song));break;
case 'music-controls-pause':this.pause();break;
case 'music-controls-play':this.play();break;
case 'music-controls-destroy':this.release();break;

 case 'music-controls-media-button-next':this.next().then((song)=>this.initialize(song));break;
 case 'music-controls-media-button-previous':this.prev().then((song)=>this.initialize(song));break;
 case 'music-controls-media-button-pause':this.pause();break;
 case 'music-controls-media-button-play':this.play();break;
 case 'music-controls-media-button-play-pause':this.tooglepp();break;
 case 'music-controls-media-button-headset-hook':this.pause();break;
 default: break;
}
});
} catch (error) {
console.log(error)
}
this.control.listen( );
this.control.updateIsPlaying(true);
}
