### ISSUE TITLE
iOS: the plugin does not work if cordova background mode is not enabled

### ISSUE THREAD

**Issue by elielnfinic** [ghenry22/cordova-plugin-music-controls2#44]
Hello everybody,

I am trying to use this plugin but if I do not enable cordova background mode, it does not show the track different track info(+cover image) and the previous and next buttons are not working.

Is there a possibility to fix this because cordova background mode is stop audio of other apps and my app.

Thank you.

**Comment by ghenry22** [comment]
This is not a problem with this plugin, this is the way that iOS works unfortunately.

You can use my fork of the background mode plugin that removes the nasty fake audio that causes this problem.

https://github.com/ghenry22/cordova-plugin-background-mode

Note that you still need the background mode capability enabled in xcode with the appropriate use case (ie audio and airplay).
