### ISSUE TITLE
Service should be running in foreground mode

### ISSUE THREAD

**Issue by TitanNano** [ghenry22/cordova-plugin-music-controls2#46]
We are facing the issue that Android (at least 10+) is killing our network connection and thereby also our audio stream after about ~5 minutes. 
The problem appears to be, that the service created by this plugin is not running in foreground mode. Calling `startForeground` in the service, is currently fixing our issue. I will create a pull request that should fix this problem.

**Comment by TitanNano** [comment]
@ghenry22 what do you think about our PR?

**Comment by ghenry22** [comment]
Thanks for reporting, I will take a look at this for sure. Just need to buy a newer android test phone!

**Comment by ghenry22** [comment]
I have merged into development branch, looks good on my device, will merge back into master and push a new version by end of the week.

**Comment by ghenry22** [comment]
This has been merged and released in 3.0.6, thanks for the PR!
