### ISSUE TITLE
Control media from external bluetooth device

### ISSUE THREAD

**Issue by f18nfz** [ghenry22/cordova-plugin-music-controls2#48]
When implementing this on Android I seem to be unable to view or control the media playback using external bluetooth devices - (like my Mi Band 4). - (It doesn't pick up that music is playing). Does this feature work for others or any suggestions on how to get it to work?
Thanks

**Comment by ghenry22** [comment]
Bluetooth controls should be working in 3.0.6, I have tested with Sony and Jabra bluetooth headsets and all standard controls (play/pause/next/prev/volume) work as expected
