### ISSUE TITLE
README installation seems wrong

### ISSUE THREAD

**Issue by alexhorner** [ghenry22/cordova-plugin-music-controls2#49]
I'm not the best with Node, and especially not Cordova, however it seems the suggested `npm install cordova-plugin-music-controls2` installation command did not work for me, however `cordova plugin add cordova-plugin-music-controls2` did work.

**Comment by alexhorner** [comment]
Just to expand, the module did install correctly, however was not picked up by Cordova and made available for use

**Comment by ghenry22** [comment]
Thanks for flagging that I will update the readme

**Comment by ghenry22** [comment]
fixed thanks!
