### ISSUE TITLE
Install url

### ISSUE THREAD

**Issue by matias-tecnosoul** [ghenry22/cordova-plugin-music-controls2#5]
Hello, I've noticed the install url given in the Readme is the one pointing to the Homerours github: 
> Installation
> cordova plugin add https://github.com/homerours/cordova-music-controls-plugin)

Is this correct? I mean, does this url forwards to this fork? or should I just use your github url like this:
cordova plugin add https://github.com/ghenry22/cordova-music-controls-plugin

I've tried both and got this two different results:

- original github:

```
cordova plugin add https://github.com/homerours/cordova-music-controls-plugin
cordova plugin ls
cordova-plugin-music-controls 2.2.0 "MusicControls"
```

- forked github:

```
cordova plugin add https://github.com/ghenry22/cordova-music-controls-plugin
cordova plugin ls                                                           
cordova-music-controls 2.2.1 "MusicControls"
```
Which one should I use?
Thanks!

**Comment by ghenry22** [comment]
The original repo isn't actively maintained currently, I suggest installing from this one.

I will get documentation updated and start pushing out releases to npm properly soon

**Comment by ghenry22** [comment]
this is updated now in the readme
