### ISSUE TITLE
Still getting error 'MainViewController.h' file not found

### ISSUE THREAD

**Issue by tagirahmad** [ghenry22/cordova-plugin-music-controls2#50]
Hello, I am getting the error 'MainViewController.h' file not found

<img width="865" alt="Screenshot 2021-03-20 at 11 49 55" src="https://user-images.githubusercontent.com/43289913/111864519-647b2080-8972-11eb-8ce0-dcde36d706ea.png">

**Comment by ppappukim** [comment]
did you resolved this issue? i have same issue
