### ISSUE TITLE
Clarifications & requests

### ISSUE THREAD

**Issue by seedee007** [ghenry22/cordova-plugin-music-controls2#51]
First off, thank your for creating this. It works fantastically on iOS 14.1 (currently latest version).

A couple of questions.

1. Can you explain what 'MusicControls.updateDismissable' does?
2. I would like to put an 'Airplay' button on my UIView that launches the Airplay selection modal. Is this available in your plugin? If not, do you have an idea on how that could be achieved.

Thanks again GH.

**Comment by ghenry22** [comment]
updateDismissable changes whether the notification can be dismissed by the user or not.  Doesn't apply to iOS, only for Android.

On the lockscreen remote controls you will get the airplay button automatically.

For displaying that selector within your app its not really in the scope of this project.  You can check out this plugin that I modified previously to do exactly that, you can set it to show airplay selector only and it will display this as a native component overlaid on your webview.  I haven't used it for a while but probably still works.

https://github.com/ghenry22/Cordova-Plugin-Volume
