### ISSUE TITLE
Use base64 string for image

### ISSUE THREAD

**Issue by mayankkataria** [ghenry22/cordova-plugin-music-controls2#55]
Storing an image in device storage and again retrieving from it to show in notification seems time consuming and bulky. It would be better if we are directly able to use base64 string to show image inside notification which I'm trying to achieve with below code but unable to do it
```
sampleCover = '---base64 string---';
this.musicControls.create({
      cover: this.sampleCover,      
      ...
```
No image is coming in notification through this code. Is there any workaround to show the image through base64 string?

**Comment by ghenry22** [comment]
Currently this is not supported, we pass the file url to the native plugin code that then uses it to display.  You can also pass in a HTTP/HTTPS url, doesn't have to be a local file.
