### ISSUE TITLE
Lockscreen: disabling previous / next controls

### ISSUE THREAD

**Issue by currim** [ghenry22/cordova-plugin-music-controls2#58]
First of all thanks for a very nice plugin @ghenry22  

Question: is there a way to disable the previous / next controls on the lock screen? 
In my case I'm playing one long piece of media -- and there is no previous or next media.

I tried using
 hasPrev: false,
 hasNext: false
But these will disable the controls in the notifications area (not on the lock screen). 

Thanks

**Comment by ghenry22** [comment]
Those should do what you want.  You're saying that they function as you expect on the notification but make no change on the lock screen?

Could you let me know the phone model and operating system version you are using?

**Comment by currim** [comment]
> 
> 
> Those should do what you want. You're saying that they function as you expect on the notification but make no change on the lock screen?
> 
> Could you let me know the phone model and operating system version you are using?

Thanks for the quick reply.

That's correct -- the notification area does not show any previous / next button control. However, on the lock screen -- these continue to appear.

It's Android 10 on a samsung device.

**Comment by ghenry22** [comment]
Thanks I'll take a look at it and see what I can do.

**Comment by ghenry22** [comment]
@currim want to check with you if you managed to resolve the problem or if it was fixed in the latest version?

**Comment by currim** [comment]
> 
> 
> @currim want to check with you if you managed to resolve the problem or if it was fixed in the latest version?

@ghenry22  - i ended up using it for multiple "tracks", so it wasn't a requirement for me.  I know your time is limited so I didn't want to trouble you for the feature if it wasn't "affecting" me.

Thank you for checking!

**Comment by TheHolyRoger** [comment]
@ghenry22 hey man this is still an issue for me on Samsung s9 running Android 10

**Comment by griffinwebnet** [comment]
Still an issue  for me as well. im using it for a music screaming app so prev/next have no function for a live stream.
