### ISSUE TITLE
build errors possibly related to pull requests

### ISSUE THREAD

**Issue by matias-tecnosoul** [ghenry22/cordova-plugin-music-controls2#6]
Hello, I'm getting quite a few build errors and most of them seem to be related to this pull requests:
[MediaSessionCompat error on API 20 or earlier](https://github.com/ghenry22/cordova-music-controls-plugin/pull/3)
[Added support framework](https://github.com/ghenry22/cordova-music-controls-plugin/pull/4)
I've added the plugin cordova-plugin-android-support-v4 and reduced many errors, but still getting this:

1. 

```
MediaSessionCallback.java:54: error: method does not override or implement a method from a supertype
MediaSessionCallback.java:56: error: cannot find symbol
    super.onPlayFromMediaId(mediaId, extras);
         ^
  symbol: method onPlayFromMediaId(String,Bundle)
```

2. 
```
MusicControls.java:72:` error: cannot find symbol
		this.mediaSessionCompat.setMediaButtonReceiver(this.mediaButtonPendingIntent);
		                       ^
  symbol:   method setMediaButtonReceiver(PendingIntent)
  location: variable mediaSessionCompat of type MediaSessionCompat
```

3. 
```
MusicControls.java:80: error: cannot find symbol
		this.mediaSessionCompat.setMediaButtonReceiver(null);
		                       ^
  symbol:   method setMediaButtonReceiver(<null>)
  location: variable mediaSessionCompat of type MediaSessionCompat

```
4.
```
MusicControls.java:103: error: no suitable constructor found for MediaSessionCompat(Context,String,<null>,PendingIntent)
		this.mediaSessionCompat = new MediaSessionCompat(context, "cordova-music-controls-media-session", null, this.mediaButtonPendingIntent);
		                          ^
    constructor MediaSessionCompat.MediaSessionCompat(Context,String) is not applicable
      (actual and formal argument lists differ in length)
    constructor MediaSessionCompat.MediaSessionCompat(MediaSessionImpl) is not applicable
      (actual and formal argument lists differ in length)

```

> Note: Some input files use or override a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: ...platforms/android/app/src/main/java/org/apache/cordova/file/AssetFilesystem.java uses unchecked or unsafe operations.

Is there any chances to get some hints on this??
some environment info:

cordova-lib@9.0.1 with:
  cordova-common@3.2.0
  cordova-create@2.0.0
  cordova-fetch@2.0.1
  cordova-serve@3.0.0

Environment: 
  OS: linux
  Node: v12.11.1
  npm: 6.11.3

Plugins:
  cordova-music-controls
  cordova-plugin-android-support-v4
  cordova-plugin-file
  cordova-plugin-inappbrowser
  cordova-plugin-media
  cordova-plugin-multi-player
  cordova-plugin-whitelist

Available Android targets: 100% Fetch remote repository.
  id: 1 or "android-28"
       Name: Android API 28
       Type: Platform
       API level: 28
       Revision: 6

cordova requirements android
Requirements check results for android:
Java JDK: installed 1.8.0
Android SDK: installed true
Android target: installed android-28
Gradle: installed /usr/share/java/gradle/bin/gradle

thanks in advance

**Comment by ghenry22** [comment]
I haven't had a chance to fully test those pull requests yet, hence they haven't been merged.  I will aim to do so next week and if they are working as expected will merge them in.

**Comment by mryerro** [comment]
I have migrated to androidx but problems with MediaSession got resolved adding these lines to build-extras.gradle:

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
	compile 'com.android.support:support-v4:+'
}

Can you try?

**Comment by madmandrew** [comment]
I'm also having build issues, wondering if this is still being maintained?

**Comment by ghenry22** [comment]
try adding this plugin:
https://www.npmjs.com/package/cordova-android-support-gradle-release

This tends to resolve issues with android builds and dependencies.

**Comment by ghenry22** [comment]
I've released a new build which includes the android support libraries, hopefully that will resolve these build issues, the gradle release plugin is still worth including to handle any conflicts between plugins.

**Comment by madmandrew** [comment]
I can confirm it works now!
see [issue19](https://github.com/ghenry22/cordova-plugin-music-controls2/issues/19)
