### ISSUE TITLE
'MainViewController.h' file not found

### ISSUE THREAD

**Issue by vmartins** [ghenry22/cordova-plugin-music-controls2#67]
Xcode build failed:
> /my/path/ios/capacitor-cordova-ios-plugins/sources/CordovaPluginMusicControls2/MainViewController+MusicControls.h:12:9: 'MainViewController.h' file not found

https://github.com/ghenry22/cordova-plugin-music-controls2/blob/4a2335eccc673f845cb0b6ed55fc87eb4ece843f/src/ios/MainViewController%2BMusicControls.h#L12

ionic cli: 6.16.3
xcode: 12.0 (12A7209)
cordova-plugin-music-controls2: 3.0.6
capacitor: 2.4.7

**Comment by kjakub** [comment]
same issue

**Comment by ghenry22** [comment]
This is because Capacitor does not support the mainviewcontroller implementation that cordova does. I will commit a fix for this for capacitor compatibility.

**Comment by jh-gh** [comment]
Hi @ghenry22, Do you have any estimate for when you might be able to release a version of this plugin that works with Capacitor?  Thanks.

**Comment by ShaunBrassell** [comment]
Hi Gaven @ghenry22, thanks for looking into this, also would like to know the work around for this as Capacitor seems to be the chosen way these days for Ionic. Cheers

**Comment by jh-gh** [comment]
Yes it would be really great if this plugin could support Capacitor.  In the meantime, I have been using https://github.com/ingageco/capacitor-music-controls-plugin though I'm not sure that plugin is getting much active support.       @ShaunBrassell @ghenry22 

I can't get either plugin to show any controls at all on iOS when I use them with video (using either the capacitor-video-player or the cordova-plugin-streaming-media).  But the capacitor music controls plugin does work on Android ... both with the capacitor-video-player plugin ... and when showing HTML audio.

**Comment by ShaunBrassell** [comment]
> Yes it would be really great if this plugin could support Capacitor. In the meantime, I have been using https://github.com/ingageco/capacitor-music-controls-plugin though I'm not sure that plugin is getting much active support. @ShaunBrassell @ghenry22
> 
> I can't get either plugin to show any controls at all on iOS when I use them with video (using either the capacitor-video-player or the cordova-plugin-streaming-media). But the capacitor music controls plugin does work on Android ... both with the capacitor-video-player plugin ... and when showing HTML audio.

Aaah I see that the latest code does cater for Capacitor, its just not in the 3.0.5 release which is from 2020 ... just view the latest source code, all that was required is 2 source file changes. Thanks @ghenry22

**Comment by jake-newsom** [comment]
Soooo... are we just never going to get this added to the official release?

**Comment by juanmaldonadodev** [comment]
Plugin is not working with Capacitor 3. Do you have in plan to migrate it?

**Comment by juanmaldonadodev** [comment]
I have created a plugin proposal on capacitor community: https://github.com/capacitor-community/proposals/issues/158

**Comment by ghenry22** [comment]
This has been fixed for capacitor a long time ago, please give the latest release on NPM a try and you should be good.
