### ISSUE TITLE
iOS - problem with play/pause and notification

### ISSUE THREAD

**Issue by MarcinDl** [ghenry22/cordova-plugin-music-controls2#71]
Hello,

on iOS I have two quite problems (but with videos only. Fortunately with audios everything is all right): 

1.  till the app is minimized, a notification is not visible. When I minimize an app and get back on main screen, a notifications shows up. But why does it not visible on first minimization?
2. I am able to control previous/next recording, but I can not control play/pause button (please remember, on video only and only from notification). The code I wrote seems to be ok, but from some reason it doesn't work. 

```
updateElapsed({
            elapsed: this.currentTime,
            isPlaying: this.isPlaying
          });
```

Any suggestions will be appreciate!

Cheers,
Marcin

**Comment by pp8403** [comment]
Does this plugin work on ios14?

**Comment by MarcinDl** [comment]
> Does this plugin work on ios14?

yes, it works very well. Except play/pause button. 😅

**Comment by greaterking** [comment]
any one have this working??

**Comment by ghenry22** [comment]
Works perfectly on iOS 14 & 15 for me so far but my use case is only for Audio.  I haven't tried with Video.

How are you playing the video?  With a native plugin of some sort or using HTML5 video tags?

**Comment by greaterking** [comment]
Yes I was attempting to use music controls while the same time playing the audio through HTML… It seems however that this isn’t possible as far as I can tell. Seems as if you need to use the native Cordova media plug-in in order to make this function correctly. Am I correct in this?

**Comment by ghenry22** [comment]
@greaterking yep that's right if you use HTML audio then the browser/webview will override the remote controls plugin.  If you use the cordova media plugin then it should work as you expect.

**Comment by bikubi** [comment]
@ghenry22 does that apply to play/pause *controls* only, or does this apply to the "notification" (artist/track/album) as well? I.e. when I use HTML audio, can I use the plugin to set a different artist+album, or am I stuck with the default HTML title?
(If so: when I use HTML audio, does the plugin do *anything*?)

**Comment by ghenry22** [comment]
@bikubi sorry didn't see this reply, this is woefully late!  It basically doesn't work with HTML audio as the metadata will be overriden by the HTML audio's default values.
