### ISSUE TITLE
Does not work on iOS

### ISSUE THREAD

**Issue by paulovargatt** [ghenry22/cordova-plugin-music-controls2#8]
I have problems trying to implement this plugin on IOS, all attempts I made were unsuccessful, on android works!

I tried to start this plugin without media, with video, with audio, both situations realize that it is the webview that creates the controls and not the plugin, the next and back controls are always disabled! I can't manipulate these controls created by webview? Or is there a way to replace these controls with this plugin?
![Image of Yaktocat](https://i.imgur.com/C5xbhRb.jpg)

**Comment by ghenry22** [comment]
You need to use the native media plugin in order for the remote controls to work correctly.

It is know that it doesn't work properly with HTML5 audio.

**Comment by paulovargatt** [comment]
@ghenry22  Thanks for the answer!
My need is to play a streaming url *. .m3u8 (HLS streaming)

Do you have any suggestion ?

**Comment by Ekaanth** [comment]
> @ghenry22 Thanks for the answer!
> My need is to play a streaming url *. .m3u8 (HLS streaming)
> 
> Do you have any suggestion ?

Any update? im also looking at a similar problem.

**Comment by paulovargatt** [comment]
> > @ghenry22 Thanks for the answer!
> > My need is to play a streaming url *. .m3u8 (HLS streaming)
> > Do you have any suggestion ?
> 
> Any update? im also looking at a similar problem.

The solution for me was to use https://github.com/apache/cordova-plugin-media

**Comment by tbergeron** [comment]
> The solution for me was to use https://github.com/apache/cordova-plugin-media

How to use this `cordova-plugin-media` with `cordova-music-controls`? I've been trying to get music controls working with Ionic on iOS for over a year. There's something I seem to not understand :sob:

**Comment by Ekaanth** [comment]
@paulovargatt @ghenry22 @tbergeron  any idea does 
> https://github.com/apache/cordova-plugin-media

also, support on the browser? has anyone tested?
