### ISSUE TITLE
Failed to fetch plugin

### ISSUE THREAD

**Issue by nowrap** [ghenry22/cordova-plugin-music-controls2#9]
Hello,
today we tried to install the plugin again. But i fails on windows and on os x.

We used the ionic syntax and the tried the cordova syntax:
```
ionic cordova plugin add https://github.com/ghenry22/cordova-music-controls-plugin.git
cordova plugin add https://github.com/ghenry22/cordova-music-controls-plugin
```

With the ancestor version from homerours the installation works.

Regards
nowrap

**Comment by kevryan2** [comment]
Also unable to fetch this plugin from the registry, which has essentially broken the piece of our application using this plugin.  This plugin was the only current fix for iOS 13, fingers crossed somebody is looking into the issue here.

**Comment by ghenry22** [comment]
you should definitely be able to install it directly from github as you have in the example, I will test it out today and see if there is anything wrong.

**Comment by ghenry22** [comment]
ionic cordova plugin add https://github.com/ghenry22/cordova-music-controls-plugin
or
cordova plugin add https://github.com/ghenry22/cordova-music-controls-plugin

both work fine for me, just added to a new test project without any issue.

This version of the plugin is not currently published to NPM.  I am cleaning up and renaming it now so that I can push it to NPM to make everyones life easier.

**Comment by Carlosps** [comment]
It no longer works for me. I keep getting 

> cordova plugin add https://github.com/ghenry22/cordova-music-controls-plugin
Failed to fetch plugin https://github.com/ghenry22/cordova-music-controls-plugin via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Failed to get absolute path to installed module

**Comment by cen1** [comment]
Yeah, same problem here, can't install from github. 

I went through hell with the existing 2.2.0 release just to try it out and have some fun in the ionic-conference-app sample and gave up after missing gradle dependencies for android support libraries (I see pull request is open for this one).

Fingers crossed to get a bump release that at least builds properly.

**Comment by ghenry22** [comment]
I have published an updated plugin to npm and updated the installation URLs in the readme and verified that both install from github and from npm seem to be working.  Take a look and give it a try.
